export const POST_GET_REQUEST = "POST_GET_REQUEST";
export const POST_GET_SUCCESS = "POST_GET_SUCCESS";
export const POST_GET_FAILURE = "POST_GET_FAILURE";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAILURE = "POST_LIKE_FAILURE";
